name: phoenix-rising # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Phoenix Rising Age
summary: A mythical combat adventure!
description: Harness the power of the Phoenix, build a legacy, and battle enemies in breathtaking settings.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  phoenix-rising:
    command: bin/phoenix-rising-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  phoenix-rising:
    plugin: dump
    source: .
    organize:
      phoenix-rising-bin: bin/
